# Generated by Django 4.2.7 on 2025-11-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['city', 'recorded_at'], name='data_weathe_city_c02ce9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subway_delays', models.IntegerField()),
                ('bus_delays', models.IntegerField()),
                ('active_buses', models.IntegerField()),
                ('active_trains', models.IntegerField()),
                ('avg_wait_time', models.FloatField()),
                ('recorded_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['recorded_at'], name='data_transi_recorde_bb3a05_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('sanitation', 'Sanitation'), ('transportation', 'Transportation'), ('utilities', 'Utilities'), ('public_safety', 'Public Safety'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['request_type', 'status'], name='data_servic_request_bfb255_idx'), models.Index(fields=['reported_at'], name='data_servic_reporte_3703ea_idx')],
            },
        ),
    ]
