# Generated by Django 4.2.7 on 2025-11-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
    ]
